version: "3"

services:
  web:
    image: nginx
    volumes:
      - ./config/:/etc/nginx/conf.d/:ro
      - ./public:/app
    ports:
      - "8080:80"
  rendertron:
    build: ./
    ports:
      - "3000:3000"